# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGraphicsView, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QProgressBar,
    QPushButton, QSizePolicy, QSlider, QTableView,
    QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(1039, 600)
        self.graphicsView = QGraphicsView(Widget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(20, 110, 360, 440))
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 311, 31))
        font = QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label.setFont(font)
        self.graphicsView_2 = QGraphicsView(Widget)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(390, 110, 360, 440))
        self.graphicsView_3 = QGraphicsView(Widget)
        self.graphicsView_3.setObjectName(u"graphicsView_3")
        self.graphicsView_3.setGeometry(QRect(760, 110, 270, 180))
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 60, 71, 31))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        self.label_2.setFont(font1)
        self.lineEdit = QLineEdit(Widget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(110, 60, 511, 31))
        font2 = QFont()
        font2.setItalic(True)
        self.lineEdit.setFont(font2)
        self.pushButton = QPushButton(Widget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(630, 50, 111, 51))
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.pushButton.setIcon(icon)
        self.tableView = QTableView(Widget)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(760, 10, 271, 91))
        self.progressBar = QProgressBar(Widget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(100, 560, 491, 31))
        self.progressBar.setValue(24)
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 560, 61, 31))
        font3 = QFont()
        font3.setPointSize(14)
        font3.setBold(False)
        font3.setItalic(False)
        self.label_3.setFont(font3)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.horizontalSlider = QSlider(Widget)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(770, 330, 251, 25))
        self.horizontalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.label_4 = QLabel(Widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(770, 290, 181, 31))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(Widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(980, 290, 41, 31))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(False)
        self.label_5.setFont(font4)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_12 = QLabel(Widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(710, 560, 31, 31))
        self.label_12.setPixmap(QPixmap(u"src/images/gpu.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setMargin(-7)
        self.label_8 = QLabel(Widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(600, 565, 61, 21))
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_9 = QLabel(Widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(680, 560, 21, 31))
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.groupBox = QGroupBox(Widget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(770, 430, 251, 111))
        font5 = QFont()
        font5.setPointSize(15)
        font5.setBold(True)
        self.groupBox.setFont(font5)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 30, 31, 28))
        self.label_13.setPixmap(QPixmap(u"src/images/icon_capoo.png"))
        self.label_13.setScaledContents(True)
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 70, 31, 28))
        self.label_14.setPixmap(QPixmap(u"src/images/icon_dogdog.png"))
        self.label_14.setScaledContents(True)
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(50, 30, 101, 31))
        self.label_10.setFont(font1)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(50, 70, 101, 31))
        self.label_6.setFont(font1)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(150, 30, 81, 31))
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(150, 70, 81, 31))
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_15 = QLabel(Widget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(770, 565, 61, 21))
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBox = QComboBox(Widget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(840, 560, 181, 32))

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.label.setText(QCoreApplication.translate("Widget", u"\u5496\u6ce2\u5075\u6e2c\u5668(YOLO)", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"\u6a94\u6848\u8def\u5f91", None))
        self.pushButton.setText(QCoreApplication.translate("Widget", u"\u8b80\u53d6\u6a94\u6848", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"\u8655\u7406\u9032\u5ea6", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"\u4fe1\u8cf4\u5ea6\u95a5\u503c\u8a2d\u5b9a", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"80", None))
        self.label_12.setText("")
        self.label_8.setText(QCoreApplication.translate("Widget", u"0", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"sec", None))
        self.groupBox.setTitle(QCoreApplication.translate("Widget", u"\u5075\u6e2c\u7d50\u679c", None))
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_10.setText(QCoreApplication.translate("Widget", u"\u5496\u6ce2\u5075\u6e2c\u6578\u91cf", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"\u72d7\u72d7\u5075\u6e2c\u6578\u91cf", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"0", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"0", None))
        self.label_15.setText(QCoreApplication.translate("Widget", u"\u786c\u9ad4\u52a0\u901f", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Widget", u"\u555f\u7528", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Widget", u"\u4e0d\u555f\u7528", None))

    # retranslateUi

